config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  resources :tickets
  resources :orderdetails
  resources :orders
  get 'pages/home'
  devise_for :users
  resources :products
  resources :brands
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/brand.rb
class Brand < ApplicationRecord
    has_many :product, dependent: :destroy
        
  # attr_accessor :name#, :email, :content

  # validates_presence_of :name
  # validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i
  # validates_length_of :content, :maximum => 500
end

app/models/deporte.rb
class Deporte < ApplicationRecord
end

app/models/farandula.rb
class Farandula < ApplicationRecord
end

app/models/internacional.rb
class Internacional < ApplicationRecord
end

app/models/nacional.rb
class Nacional < ApplicationRecord
end

app/models/noticium.rb
class Noticium < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :orderdetails, dependent: :destroy
  # has_many :products, through :orderdetail
end

app/models/orderdetail.rb
class Orderdetail < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/politica.rb
class Politica < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :brand
  belongs_to :user
  has_and_belongs_to_many :tickets
  accepts_nested_attributes_for :tickets
  has_many :orderdetails, dependent: :destroy
  has_many :orders, through :orderdetails

  has_one_attached :photo

end

app/models/ticket.rb
class Ticket < ApplicationRecord
  has_and_belongs_to_many :products
end

app/models/user.rb
class User < ApplicationRecord

  has_many :orders
  has_many :products

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: [:vendedor, :admin]

    def rol_por_defecto
      self.role ||= :vendedor
    end

  has_one_attached :avatar

end

app/controllers/orderdetails_controller.rb
class OrderdetailsController < ApplicationController
  before_action :set_orderdetail, only: %i[ show edit update destroy ]

  # GET /orderdetails or /orderdetails.json
  def index
    @orderdetails = Orderdetail.all
  end

  # GET /orderdetails/1 or /orderdetails/1.json
  def show
  end

  # GET /orderdetails/new
  def new
    @orderdetail = Orderdetail.new
  end

  # GET /orderdetails/1/edit
  def edit
  end

  # POST /orderdetails or /orderdetails.json
  def create
    @orderdetail = Orderdetail.new(orderdetail_params)

    respond_to do |format|
      if @orderdetail.save
        format.html { redirect_to orderdetail_url(@orderdetail), notice: "Los detalles de la orden fueron creados satisfactoriamente." }
        format.json { render :show, status: :created, location: @orderdetail }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @orderdetail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orderdetails/1 or /orderdetails/1.json
  def update
    respond_to do |format|
      if @orderdetail.update(orderdetail_params)
        format.html { redirect_to orderdetail_url(@orderdetail), notice: "Los detalles de la orden fueron actualizados satisfactoriamente." }
        format.json { render :show, status: :ok, location: @orderdetail }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @orderdetail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orderdetails/1 or /orderdetails/1.json
  def destroy
    @orderdetail.destroy

    respond_to do |format|
      format.html { redirect_to orderdetails_url, notice: "Los detalles de la orden fueron destruídos satisfactoriamente." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_orderdetail
      @orderdetail = Orderdetail.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def orderdetail_params
      params.require(:orderdetail).permit(:date_submitted, :status, :subtotal, :shipping, :tax, :total, :order_id, :product_id)
    end

    def of_current
      @user = current_user.try(:id)
      @tus_product = Product.where(["user_id = ?", @user])
      @orderdetails = Orderdetail.where(["user_id = ?", @user])
    end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/deportes_helper.rb
module DeportesHelper
end

app/helpers/nacionals_helper.rb
module NacionalsHelper
end

app/helpers/noticia_helper.rb
module NoticiaHelper
end

app/helpers/orderdetails_helper.rb
module OrderdetailsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/orderdetails/_form.html.erb
<%= form_with(model: orderdetail) do |form| %>
  <% if orderdetail.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(orderdetail.errors.count, "error") %> prohibited this orderdetail from being saved:</h2>

      <ul>
        <% orderdetail.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :date_submitted, style: "display: block" %>
    <%= form.time_field :date_submitted %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.number_field :status %>
  </div>

  <div>
    <%= form.label :subtotal, style: "display: block" %>
    <%= form.text_field :subtotal %>
  </div>

  <div>
    <%= form.label :shipping, style: "display: block" %>
    <%= form.text_field :shipping %>
  </div>

  <div>
    <%= form.label :tax, style: "display: block" %>
    <%= form.text_field :tax %>
  </div>

  <div>
    <%= form.label :total, style: "display: block" %>
    <%= form.text_field :total %>
  </div>

  <div>
    <%= form.label :order_id, style: "display: block" %>
    <%= form.text_field :order_id %>
  </div>

  <div>
    <%= form.label :product_id, style: "display: block" %>
    <%= form.text_field :product_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/orderdetails/_orderdetail.html.erb
<div id="<%= dom_id orderdetail %>">
  <p>
    <strong>Date submitted:</strong>
    <%= orderdetail.date_submitted %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= orderdetail.status %>
  </p>

  <p>
    <strong>Subtotal:</strong>
    <%= orderdetail.subtotal %>
  </p>

  <p>
    <strong>Shipping:</strong>
    <%= orderdetail.shipping %>
  </p>

  <p>
    <strong>Tax:</strong>
    <%= orderdetail.tax %>
  </p>

  <p>
    <strong>Total:</strong>
    <%= orderdetail.total %>
  </p>

  <p>
    <strong>Order:</strong>
    <%= orderdetail.order_id %>
  </p>

  <p>
    <strong>Product:</strong>
    <%= orderdetail.product_id %>
  </p>

</div>

app/views/orderdetails/edit.html.erb
<h1>Editing orderdetail</h1>

<%= render "form", orderdetail: @orderdetail %>

<br>

<div>
  <%= link_to "Show this orderdetail", @orderdetail %> |
  <%= link_to "Back to orderdetails", orderdetails_path %>
</div>

app/views/orderdetails/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Orderdetails</h1>

<div id="orderdetails">
  <% @orderdetails.each do |orderdetail| %>
    <%= render orderdetail %>
    <p>
      <%= link_to "Show this orderdetail", orderdetail %>
    </p>
  <% end %>
</div>

<%= link_to "New orderdetail", new_orderdetail_path %>

app/views/orderdetails/new.html.erb
<h1>New orderdetail</h1>

<%= render "form", orderdetail: @orderdetail %>

<br>

<div>
  <%= link_to "Back to orderdetails", orderdetails_path %>
</div>

app/views/orderdetails/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @orderdetail %>

<div>
  <%= link_to "Edit this orderdetail", edit_orderdetail_path(@orderdetail) %> |
  <%= link_to "Back to orderdetails", orderdetails_path %>

  <%= button_to "Destroy this orderdetail", @orderdetail, method: :delete %>
</div>