config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  resources :tickets
  resources :orderdetails
  resources :orders
  get 'pages/home'
  devise_for :users
  resources :products
  resources :brands
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/brand.rb
class Brand < ApplicationRecord
    has_many :product, dependent: :destroy
        
  # attr_accessor :name#, :email, :content

  # validates_presence_of :name
  # validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i
  # validates_length_of :content, :maximum => 500
end

app/models/deporte.rb
class Deporte < ApplicationRecord
end

app/models/farandula.rb
class Farandula < ApplicationRecord
end

app/models/internacional.rb
class Internacional < ApplicationRecord
end

app/models/nacional.rb
class Nacional < ApplicationRecord
end

app/models/noticium.rb
class Noticium < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :orderdetails, dependent: :destroy
  # has_many :products, through :orderdetail
end

app/models/orderdetail.rb
class Orderdetail < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/politica.rb
class Politica < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :brand
  belongs_to :user
  has_and_belongs_to_many :tickets
  accepts_nested_attributes_for :tickets
  has_many :orderdetails, dependent: :destroy
  has_many :orders, through :orderdetails

  has_one_attached :photo

end

app/models/ticket.rb
class Ticket < ApplicationRecord
  has_and_belongs_to_many :products
end

app/models/user.rb
class User < ApplicationRecord

  has_many :orders
  has_many :products

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: [:vendedor, :admin]

    def rol_por_defecto
      self.role ||= :vendedor
    end

  has_one_attached :avatar

end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_brand, only: %i[ show edit update destroy ]
  before_action :of_current, only: %i[ new index edit ]

  # GET /brands or /brands.json
  def index
    @brands = Brand.all
  end

  # GET /brands/1 or /brands/1.json
  def show
  end

  # GET /brands/new
  def new
    @brand = Brand.new
    @product = Product.all
  end

  # GET /brands/1/edit
  def edit
  end

  # POST /brands or /brands.json
  def create
    @brand = Brand.new(brand_params)

    respond_to do |format|
      if @brand.save
        format.html { redirect_to brand_url(@brand), notice: "La marca fue creada satisfactoriamente." }
        format.json { render :show, status: :created, location: @brand }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brands/1 or /brands/1.json
  def update
    respond_to do |format|
      if @brand.update(brand_params)
        format.html { redirect_to brand_url(@brand), notice: "La marca fue actualizada satisfactoriamente." }
        format.json { render :show, status: :ok, location: @brand }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brands/1 or /brands/1.json
  def destroy
    @brand.destroy

    respond_to do |format|
      format.html { redirect_to brands_url, notice: "La marca fue destruída satisfactoriamente." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brand
      @brand = Brand.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def brand_params
      params.require(:brand).permit(:nombre, :user_id, :product_id)
    end

    def of_current
      @user = current_user.try(:id)
      @tus_product = Product.where(["user_id = ?", @user])
      @brands = Brand.where(["user_id = ?", @user])
    end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/deportes_helper.rb
module DeportesHelper
end

app/helpers/nacionals_helper.rb
module NacionalsHelper
end

app/helpers/noticia_helper.rb
module NoticiaHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/politicas_helper.rb
module PoliticasHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/brands/_brand.html.erb
<div id="<%= dom_id board %>">
  <div class="card">
    <h5 class="card-header"><%= brand.nombre %></h5>
    <div class="card-body">
      <h6 class="card-title">Nombre:</h6>
      <p class="card-text"><%= brand.product.name %></p>
    </div>
  </div>
</div>

app/views/brands/_form.html.erb
<%= form_with(model: brand) do |form| %>
  <% if brand.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(brand.errors.count, "error") %> prohibited this brand from being saved:</h2>

      <ul>
        <% brand.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nombre, "Título de la marca:", style: "display: block" %>
    <%= form.text_field :nombre %>
  </div>

  <div>
    <% form.label :user_id %>
    <%= form.hidden_field :user_id, value: @user %>
  </div>

  <div>
    <%= form.label :product_id, "Elige un producto:", style: "display: block", class: "mt-3"  %>
    <%= form.collection_select :product_id, @tus_product, :id, :name  %>
  </div>

  <div>
    <%= form.submit "Crear", class: "btn btn-warning mt-4 btn-lg" %>
  </div>
<% end %>

app/views/brands/edit.html.erb
<h1>Editando la marca</h1>

<%= render "form", brand: @brand %>

<br>

<div>
  <%= link_to "Mostrar esta marca", @brand %> |
  <%= link_to "Volver a marcas", brands_path %>
</div>

app/views/brands/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tus marcas</h1>
<p class="lead" >Solo puedes ver las marcas que han sido creadas por ti </p>
<%= link_to "Crear marca", new_brand_path, class: "btn btn-warning mb-4" %>

<div id="brands">
  <% @brands.each do |brand| %>
    <%= render brand %>
    <p>
      <%= link_to "Mostrar esta marca", brand %>
    </p>
  <% end %>
</div>

<%= link_to "Nueva marca", new_brand_path %>

app/views/brands/new.html.erb
<h1>Nueva marca</h1>
<p class="lead" >Crea una marca para uno de tus productos:</p>

<%= render "form", brand: @brand %>

<br>

<div>
  <%= link_to "Volver a marcas", brands_path, class: "btn btn-secondary mb-4 btn-sm" %>
</div>

app/views/brands/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @brand %>

<div>
  <%= link_to "Editar esta marca", edit_brand_path(@brand) %> |
  <%= link_to "Volver a marcas", brands_path %>

  <%= button_to "Destruir esta marca", @brand, method: :delete, class: "btn btn-outline-danger btn-sm mt-2" %>
</div>