config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  resources :tickets
  resources :orderdetails
  resources :orders
  get 'pages/home'
  devise_for :users
  resources :products
  resources :brands
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/brand.rb
class Brand < ApplicationRecord
    has_many :product, dependent: :destroy
        
  # attr_accessor :name#, :email, :content

  # validates_presence_of :name
  # validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i
  # validates_length_of :content, :maximum => 500
end

app/models/deporte.rb
class Deporte < ApplicationRecord
end

app/models/farandula.rb
class Farandula < ApplicationRecord
end

app/models/internacional.rb
class Internacional < ApplicationRecord
end

app/models/nacional.rb
class Nacional < ApplicationRecord
end

app/models/noticium.rb
class Noticium < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :orderdetails, dependent: :destroy
  # has_many :products, through :orderdetail
end

app/models/orderdetail.rb
class Orderdetail < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/politica.rb
class Politica < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :brand
  belongs_to :user
  has_and_belongs_to_many :tickets
  accepts_nested_attributes_for :tickets
  has_many :orderdetails, dependent: :destroy
  has_many :orders, through :orderdetails

  has_one_attached :photo

end

app/models/ticket.rb
class Ticket < ApplicationRecord
  has_and_belongs_to_many :products
end

app/models/user.rb
class User < ApplicationRecord

  has_many :orders
  has_many :products

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: [:vendedor, :admin]

    def rol_por_defecto
      self.role ||= :vendedor
    end

  has_one_attached :avatar

end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/deportes_helper.rb
module DeportesHelper
end

app/helpers/noticia_helper.rb
module NoticiaHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="container footer" style="background-color: #9fa8da;">
    <h2>Contribuye con noticias positivas</h2>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark" style="background-color: black;">
  <div class="container-fluid">
    <%= link_to "www.babyshop.cl", root_path, class: "navbar-brand colorbrand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Inicio", root_path, class: "nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "Tus Productos", products_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Tus Órdenes", orders_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Ver Etiquetas", tickets_path, class: "nav-link" %>
        </li>
      </ul>
      <div>
        <% if user_signed_in? %>
          <%= button_to( "Salir", destroy_user_session_path, method: :delete, class: "btn btn-danger btn-sm" ) %>
        <% else %>
          <%= link_to "Registrar", new_user_registration_path, class: "btn btn-warning btn-sm" %>
          <%= link_to "Ingresar", new_user_session_path, class: "btn btn-success btn-sm"  %>
        <% end %>
      </div>
    </div>
  </div>
</nav>
  <form class="d-flex">
    <%= form_with url: products_path, method: :get do |f| %>
      <%= f.text_field :search, :class => "form-control me-2", placeholder: "Buscar en Tus Productos" %>
      <%= f.submit "Buscar", :class => "btn btn-info" %>
    <% end %> 
  </form>
<%= image_tag "banner-accesorios.jpg", class: "w-100 mt-3" %>
<% if user_signed_in? %>
  <span class="lead colorbrand" >¡Hola <%= current_user.name %>!</span>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Baby Shop (M09 AE05 Grupal)</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= javascript_importmap_tags %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

  </head>

  <body>
    <div class="container">
      <%= render "layouts/navbar"%>
      <%= yield %>
      </div>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Bienvenidos</h1>
<p>Vende tus productos</p>

<% if current_user  %>
  <h2>Hola [<%= current_user.role %>] <%= current_user.email %>  <% @a %></h2>
  <p>Productos</p>
  <%#= link_to "Sign out", destroy_user_session_path,  data: { turbo_method: :get }  %>

  <% 50.times do |i|  %>
    <div class="card" style="margin-bottom: 15px;">
      <div class="card-body">
        Producto <%= i %>
      </div>
    </div>
  <% end  %>

<% else %>

  <p>Inicie su sesion para ver los productos</p>
  <%= link_to "Click aqui para registrarse", new_user_registration_path %>
  <br>
  <%= link_to "Ingrese si es usuario!", new_user_session_path  %>

<% end %>